- name: Add docker-compose.yml and start docker-compose
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    
    - name:  Copy
      copy:
        src: docker-compose.yml
        dest: /opt/wp
        owner: alex
        group: root
        mode: u=rw,g=r,o=r

    - name: Start Docker-compose
      command: 'docker-compose up -d' 
