- name: Add docker-compose.yml and start docker-compose
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    
    - name:  Copy
      copy:
        src: docker-compose.yml
        dest: /usr/local/bin/
        owner: ubuntu
        group: ubuntu
        mode: 'a+x'

    - name: Start Docker-compose     
      command: 'docker-compose up -d' 