wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
     - WORDPRESS_DB_USER=root
    ports:
     - 80:80
    volumes:
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql